{'application':{'type':'Application',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'bgMin',
          'title':'Water Maze',
          'size':(1195, 913),
          'backgroundColor':(192, 192, 192),

         'components': [

{'type':'TextArea', 
    'name':'conversation', 
    'position':(29, 596), 
    'size':(1134, 187), 
    'backgroundColor':(212, 212, 212, 255), 
    'text':'', 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(607, 405), 
    'size':(542, 166), 
    'label':'The Other Team', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(52, 153), 
    'size':(537, 422), 
    'label':'Observation Window', 
    },

{'type':'Image', 
    'name':'imgClock', 
    'position':(442, 8), 
    'size':(136, 120), 
    'backgroundColor':(192, 192, 192, 255), 
    'file':'../../../../Documents and Settings/meisi/My Documents/My Pictures/water maze/clock.JPG', 
    },

{'type':'Flash', 
    'name':'imgRat', 
    'position':(110, 190), 
    'file':'file://C:\\Documents and Settings\\meisi\\My Documents\\My Pictures\\water maze\\shocking.swf', 
    },

{'type':'StaticText', 
    'name':'money', 
    'position':(784, 56), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 20}, 
    'foregroundColor':(255, 0, 0, 255), 
    'text':'Your Money Left: 1000', 
    },

{'type':'StaticText', 
    'name':'day', 
    'position':(94, 35), 
    'size':(125, 57), 
    'backgroundColor':(192, 192, 192, 255), 
    'border':'none', 
    'editable':False, 
    'font':{'faceName': 'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 28}, 
    'foregroundColor':(255, 0, 0, 255), 
    'text':'Day 1', 
    },

{'type':'Tree', 
    'name':'labrat1', 
    'position':(666, 275), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Tree', 
    'name':'labrat2', 
    'position':(960, 275), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Tree', 
    'name':'streetrat', 
    'position':(813, 275), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Tree', 
    'name':'other3', 
    'position':(962, 452), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Tree', 
    'name':'other2', 
    'position':(813, 450), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Tree', 
    'name':'other1', 
    'position':(666, 450), 
    'size':(124, 61), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(14, 799), 
    'size':(1156, 7), 
    'layout':'horizontal', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(35, 10), 
    'size':(1126, 116), 
    'backgroundColor':(192, 192, 192, 255), 
    'foregroundColor':(128, 128, 128, 255), 
    },



{'type':'Choice', 
    'name':'object', 
    'position':(186, 819), 
    'size':(94, -1), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'items':['labrat1','labrat2','streetrat'], 
    'stringSelection':'labrat1',
    },

{'type':'Button', 
    'name':'Submit', 
    'position':(883, 823), 
    'label':'Submit', 
    },

{'type':'Choice', 
    'name':'actionchoice', 
    'position':(484, 820), 
    'size':(252, -1), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'items':['buyLR'],
    'stringSelection':'buyLR',
    },

{'type':'RadioGroup', 
    'name':'viewrat', 
    'position':(674, 173), 
    'size':(433, 59), 
    'items':['cage for lab rat 1', 'cage for lab rat 2', 'cage for street rat'], 
    'label':'Select a Cage to Observe', 
    'layout':'horizontal', 
    'max':1, 
    'stringSelection':'cage for street rat', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(605, 144), 
    'size':(543, 227), 
    'label':'Your Team', 
    },

] # end components
} # end background
] # end backgrounds
} }
