##bad story:
##    story that ends too soon
##    story that characters keep on repeating their actions

## working configuration
## red, 2, 2
## wolf depth 2, 1

from teamwork.agent.AgentClasses import *
from teamwork.dynamics.pwlDynamics import *

from RedRidingHoodDynamics import *

classHierarchy['character'] = {
    'parent': [],
    'horizon':1,
    'depth':2,
    'dynamics':[DynFun['basicDyn'],DynFun['RedDyn']],
    'state':{\
            'type':0.0,
            'being-greeted':0.0,
            'being-byed':0.0,
            'being-enquired':0.0,

            'greeted':0.0,
            'byed':0.0,

            'conversation':0.0,
            
            'init-norm':0.0,
            'resp-norm':0.0,
            'makeResp-norm':0.0,
            'conversation-flow-norm':0.0,
            'noRepeat-norm':0.0,
            
            'alive':1.0,
            'sameLocation':1.0,
            'actAlive':1.0,
            'noRepeat':1.0,
##            'preferWait':1,

            'likeMove':-1,
            'likeTalk':-1,
            'specialRule':1.0,
             },
     'models': {
        'simple': {'goals':[\
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
                            
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'alive','weight':1000},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'actAlive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'sameLocation','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
##                             {'entity':['self'],'direction':'min','type':'state',
##                              'key':'preferWait','weight':.1},
                            ],
                'policy': [],
                     },
        'evil': {'goals':[\
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
                            
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'alive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'actAlive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'sameLocation','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
##                             {'entity':['self'],'direction':'min','type':'state',
##                              'key':'preferWait','weight':.1},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'full','weight':5.},
                            ],
                'policy': [],
                     },

     'good': {'goals':[\
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
                            
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'alive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'actAlive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'sameLocation','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
##                             {'entity':['self'],'direction':'min','type':'state',
##                              'key':'preferWait','weight':.1},
                            {'entity':['self'],'direction':'min','type':'state',
                              'key':'full','weight':.1},
                            ],
                'policy': [],
                     },

                
    'shy': {'goals':[\
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
                            
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'alive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'actAlive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'sameLocation','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
##                             {'entity':['self'],'direction':'min','type':'state',
##                              'key':'preferWait','weight':.1},
                            {'entity':['self'],'direction':'min','type':'state',
                              'key':'likeTalk','weight':1},

                            ],
                'policy': [],
                     },
        'talktive': {'goals':[\
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
                            
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'alive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'actAlive','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                              'key':'sameLocation','weight':1000.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'specialRule','weight':1000.},
##                             {'entity':['self'],'direction':'min','type':'state',
##                              'key':'preferWait','weight':.1},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'likeTalk','weight':1},

                            ],
                'policy': [],
                     },
                },
    }
classHierarchy['red'] = {
    'parent': ['character'],
    'horizon':2,
    'depth':2,
    'state':{\
            'has-cake':1.0,
            
            'location':0,

            'told-about-granny':0.0,
            'given-cake':0.0,

            'SDwithWolf':-.19,
            'being-enquired-about-granny':0,

             },
##    'beliefs':{'hunter':{'model':'simple'},
##               'granny':{'model':'simple'},
##               'wolf':{'model':'simple'},
##               },
    'goals':[\
            {'entity':['self'],'direction':'max','type':'state',
                'key':'init-norm','weight':1.},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'resp-norm','weight':1000.},
            {'entity':['self'],'direction':'max','type':'state',
                'key':'makeResp-norm','weight':1.},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'conversation-flow-norm','weight':1.},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'noRepeat-norm','weight':1.},

             {'entity':['self'],'direction':'max','type':'state',
              'key':'alive','weight':5.},
##            {'entity':['wolf'],'direction':'min','type':'state',
##              'key':'alive','weight':1.},
##             {'entity':['granny'],'direction':'max','type':'state',
##              'key':'alive','weight':1.},
             {'entity':['granny'],'direction':'max','type':'state',
              'key':'has-cake','weight':1.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'actAlive','weight':1000.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'sameLocation','weight':1000.},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'specialRule','weight':1000.},
            
##             {'entity':['self'],'direction':'max','type':'state',
##              'key':'preferWait','weight':.1},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'likeMove','weight':.5},
            {'entity':['self'],'direction':'max','type':'state',
              'key':'likeTalk','weight':.5},
             ],
     'actions': {'type':'OR',
		'values':[{'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'wolf'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[\
                                                       {'type':'literal','value':'tell-about-granny'},
                                                       {'type':'literal','value':'inform-about-granny'},
                                                       {'type':'literal','value':'escape'},
                                                       {'type':'literal','value':'greet-init'},
                                                       {'type':'literal','value':'greet-resp'},
                                                       {'type':'literal','value':'bye-init'},
                                                       {'type':'literal','value':'bye-resp'},
                                                       {'type':'literal','value':'enquiry'},
                                                       {'type':'literal','value':'inform'},
                                                       {'type':'literal','value':'give-cake'},
##                                                       {'type':'literal','value':'kill'},
##                                                       {'type':'literal','value':'follow'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'granny'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'give-cake'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'move2'},
                                                       {'type':'literal','value':'wait'},
						       ],
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'hunter'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'enquiry'},
						       ],
					     },
				    },
			   },
			  ],
		},

    }

classHierarchy['hunter'] = {
    'parent': ['character'],
##    'horizon':1,
    'depth':1,
    'state':{\
            'location':-.6,
            'likeMove':-1,
             },
    'beliefs':{'red':{'model':'simple'},
               'granny':{'model':'simple'},
               'wolf':{'model':'simple'},
               },
    'goals':[\
        {'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                        {'entity':['self'],'direction':'max','type':'state',
                                'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
        
             {'entity':['wolf'],'direction':'min','type':'state',
              'key':'alive','weight':1.},

             {'entity':['self'],'direction':'max','type':'state',
              'key':'actAlive','weight':1000.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'sameLocation','weight':1000.},
##             {'entity':['self'],'direction':'max','type':'state',
##              'key':'preferWait','weight':1},

            {'entity':['self'],'direction':'max','type':'state',
              'key':'likeMove','weight':.5},
                     {'entity':['self'],'direction':'max','type':'state',
              'key':'likeTalk','weight':.5},
             ],
     'actions': {'type':'OR',
		'values':[{'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'wolf'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'kill'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'red'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'inform'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'move2'},
                                                       {'type':'literal','value':'wait'},
						       ],
				    },
			   },
                          
			  ],
		},

    }

classHierarchy['granny'] = {
    'parent': ['character'],
##    'horizon':0,
    'depth':1,
    'state':{\
            'has-cake':0.0,
            'location':0.4,
            
             },
    'beliefs':{'red':{'model':'simple'},
               'hunter':{'model':'simple'},
               'wolf':{'model':'simple'},
               },
    'goals':[\
             {'entity':['self'],'direction':'max','type':'state',
              'key':'alive','weight':5.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'actAlive','weight':1000.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'sameLocation','weight':1000.},
             
             {'entity':['self'],'direction':'max','type':'state',
              'key':'has-cake','weight':1},
##             {'entity':['self'],'direction':'max','type':'state',
##              'key':'preferWait','weight':1},
             ],
     'actions': {'type':'OR',
		'values':[{'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'wolf'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'escape'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'wait'},
						       ],
				    },
			   },
			  ],
		},

    }

classHierarchy['wolf'] = {
    'parent': ['character'],
    'horizon':2,
    'depth':2,
    'state':{\
            'location':-.2,
            'full':0.0,
            
            'know-granny':0.0,          

            'enquired':0.0,
##            'noRepeat':1.0,

            'SDnorm':0.0,

            'preferWait':-1,
             },
##    'beliefs':{'hunter':{'model':'simple'},
##               'granny':{'model':'simple'},
##               'red':{'model':'simple'},
##               },
    'goals':[{'entity':['self'],'direction':'max','type':'state',
                              'key':'init-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'resp-norm','weight':1000.},
                             {'entity':['self'],'direction':'max','type':'state',
                            'key':'makeResp-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'conversation-flow-norm','weight':1.},
                            {'entity':['self'],'direction':'max','type':'state',
                              'key':'noRepeat-norm','weight':1.},
             
             {'entity':['self'],'direction':'max','type':'state',
              'key':'SDnorm','weight':1.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'full','weight':3.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'alive','weight':5.},
              {'entity':['self'],'direction':'max','type':'state',
              'key':'know-granny','weight':1.},
             
             {'entity':['self'],'direction':'max','type':'state',
              'key':'actAlive','weight':1000.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'sameLocation','weight':1000.},
             {'entity':['self'],'direction':'max','type':'state',
              'key':'specialRule','weight':1000.},
             
             {'entity':['self'],'direction':'max','type':'state',
              'key':'preferWait','weight':.1},

             {'entity':['self'],'direction':'max','type':'state',
              'key':'likeMove','weight':.5},
                     {'entity':['self'],'direction':'max','type':'state',
              'key':'likeTalk','weight':.5},

            
             ],
    
     'actions': {'type':'OR',
		'values':[{'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'red'},
                                              {'type':'generic','value':'granny'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'eat'},
						       ],
					     },
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'red'},
                                              ],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[\
                                                       {'type':'literal','value':'greet-init'},
                                                       {'type':'literal','value':'greet-resp'},
                                                       {'type':'literal','value':'bye-init'},
                                                       {'type':'literal','value':'bye-resp'},
                                                       {'type':'literal','value':'enquiry'},
                                                       {'type':'literal','value':'enquiry-about-granny'},
                                                       {'type':'literal','value':'inform'},
						       ],
					     },
				    },
			   },
                       
                          {'type':'decision',
                                   'value':{'type':'XOR',
                                                     'key':'type',
                                                     'values':[{'type':'literal','value':'move2'},
                                                               {'type':'literal','value':'wait'},
##                                                                {'type':'literal','value':'changeIdentity'},
                                                               ],
                                                    
                                            },
                                   }, 
			  ],
		},
    }

classHierarchy['fairy'] = {
    'parent': ['Entity'],
    'horizon':1,
    'depth':0,
    'goals':[{'entity':['self'],'direction':'min','type':'state',
              'key':'preferWait','weight':1},],
    'state':{\
            'alive':1,
             },
    'dynamics':[],
     'actions': {'type':'OR',
		'values':[{'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'wolf'}],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'kill'},
						       ],
					     },
				    },
			   },
                          
                          {'type':'decision',
			   'value':{'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'wait'},
						       ],
				    },
			   },
                          {'type':'decision',
			   'value':{'type':'XOR',
				    'key':'object',
				    'values':[{'type':'generic','value':'red'},
                                              {'type':'generic','value':'granny'},
                                              {'type':'generic','value':'wolf'},],
				    'base': {'type':'XOR',
					     'key':'type',
					     'values':[{'type':'literal','value':'resurrect'},
						       ],
					     },
				    },
			   },
			  ],
		},

    }

