"""
@var WAYPOINTS: A table of waypoint information across all six levels
@var OLDWAYPOINTS: The old table of waypoint information across three levels
"""
WAYPOINTS = [
    [ # Level 1
        {'name': 'Warehouse',
         'image': 'Empty_Storage_Room',
         'comment': 'An empty storage room',
         'start': True,
        },
        {'name': 'Blue Mosque',
         'image': 'Blue_Mosque',
         'comment': 'Filled with people in their daily prayers',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
        {'name': 'Back Alley',
         'image': 'Cracked-Wall-Room',
         'comment': 'Unoccupied corridor between two buildings',
        },
        {'name': 'Cleric\'s House',
         'image': 'Carpet-Room',
         'comment': 'Unoccupied building, seemingly abandoned',
         'symbol': 'ClericsHouse',
        },
        {'name': 'Courthouse',
         'image': 'Doctor\'s_Office',
         'comment': 'Empty waiting area within city courthouse',
        },
        {'name': 'Unemployment Office',
         'image': 'City_Office',
         'comment': 'Angry civilians waiting in line, but not violent',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
        {'name': 'Faith Mosque',
         'comment': 'Currently empty of civilians. Nothing of interest',
         'image': 'Yellow_Mosque',
        },
        {'name': 'City Office',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Armed insurgent in back room of city office building',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
        {'name': 'Furniture Store',
         'image': 'Furniture_Store',
         'comment': 'Salesman and customer haggling in furniture showroom',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
        {'name': 'Doctor\'s Office',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Occupied by two armed insurgents',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
         'symbol': 'DoctorsOffice',
        },
        {'name': 'Opium Den',
         'image': 'Cafe',
         'comment': 'Hookah smoke and customers, but nothing dangerous',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
        {'name': 'Animal Feed Store',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Taken over by armed insurgents who were hiding the hostage',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
        {'name': 'Black Market',
         'image': 'Black_Market',
         'comment': 'Unarmed man illegally selling clothing in the back room',
        },
        {'name': 'Outdoor Landing',
         'image': 'Potential_Sniper_Spot',
         'comment': 'Outdoor space with nothing of interest',
        },
        {'name': 'Farm Supply Store',
         'image': 'Farm_Supply_Store_danger',
         'comment': 'Toxic chemicals being stored in open drums',
         'NBC': True,
         'NBCsensor': {True: True,
                       False: True},
         'symbol': 'FarmSupply',
        },
        ],
    [ # Level 2
	{'name': 'Accounting Office',
         'image': 'Furniture_Store',
         'comment': 'Accountants discussing finances',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'start': True,
        },
	{'name': 'Hookah Cafe',
         'image': 'Cafe_danger',
         'comment': 'Hookah smoke being used to mask the smell of toxic chemicals',
         'NBC': True,
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: True,
                       False: True},
        },
	{'name': 'Elementary School',
         'image': 'Poster-Room',
         'comment': 'Currently empty; children have already gone home',
        },
	{'name': 'Suspected Safe House',
         'image': 'Suspected_Safe_House',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'Civilians having private dinner and a friendly argument',
         'symbol': 'SafeHouse',
        },
	{'name': 'Abandoned Restaurant',
         'image': 'Cracked-Wall-Room',
         'comment': 'Graffiti covered walls of unoccupied stall',
        },
	{'name': 'Radical Cleric\'s House',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Confrontation with two armed bodyguards',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
         'symbol': 'RadicalHouse',
        },
	{'name': 'Yellow Mosque',
         'comment': 'Currently empty of civilians. Nothing of interest',
         'image': 'Yellow_Mosque',
        },
	{'name': 'Book Depository',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Armed insurgent in unused warehouse',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Registration Office',
         'image': 'City_Office',
         'comment': 'Bored civilians, peacefully waiting in line',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Mullah\'s House',
         'image': 'Carpet-Room',
         'comment': 'Empty waiting room with no visitors',
         'symbol': 'MullahsHouse',
        },
	{'name': 'Auto Parts Store',
         'image': 'Auto_Parts_Store',
         'comment': 'Salesmen and customers in front room',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Mosque',
         'image': 'Blue_Mosque_hostage',
         'comment': 'Peaceful female civilians praying in front, hostage found restrained in corner behind screen',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'hostage': True,
        },
	{'name': 'Fuel Store',
         'image': 'Farm_Supply_Store',
         'comment': 'Safe other than some drums of fuel',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: False,
                       False: False},
        },
	{'name': 'Unknown Residence',
         'image': 'Informant\'s_House',
         'comment': 'Came across a family in the middle of their prayers',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Food Bank',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Interrupted armed insurgents attempting to steal food',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
        ],
    [ # Level 3
	{'name': 'Apartment Building',
         'image': 'Chat-Room',
         'comment': 'Tenants milling about in the hallway',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'start': True,
        },
	{'name': 'Conference Center',
         'image': 'Wall-Table-Room',
         'comment': 'Traces of a previous meeting and presentation',
        },
	{'name': 'Gambling Parlour',
         'image': 'Cafe_danger',
         'comment': 'Civilians gambling in front room, but insurgent constructing dirty bomb in back',
         'NBC': True,
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: True,
                       False: True},
        },
	{'name': 'Friday Mosque',
         'image': 'Blue_Mosque_hostage',
         'comment': 'Civilians praying quietly in the front, male hostage found hidden behind screen',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'hostage': True,
        },
	{'name': 'Water Plant',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Cornered lone gunman near emergency exit',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Tenement Building',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Insurgents in the basement, hiding both explosives and the hostage',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Great Mosque',
         'image': 'Blue_Mosque',
         'comment': 'Filled with people doing their daily prayers',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },                  
	{'name': 'NGO Office',
         'image': 'Furniture_Store',
         'comment': 'Aid worker conversing with local official',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Coffee Shop',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Two insurgents laying in ambush',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
	{'name': 'Missionary Center',
         'image': 'Carpet-Room',
         'comment': 'Nothing of interest; seemingly abandoned',
        },
	{'name': 'Granary',
         'image': 'Auto_Parts_Store',
         'comment': 'People haggling over the price of rice, grain, etc.',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'General Store',
         'image': 'Gas_Room',
         'comment': 'Oil spill in storage room of general store, but nothing dangerous',
        },
	{'name': 'Motor Vehicle Registration',
         'image': 'City_Office',
         'comment': 'Slow-moving lines of annoyed civilians',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Grand Hotel',
         'image': 'Doctor\'s_Office',
         'comment': 'No suspicious persons in lobby',
        },
	{'name': 'Industrial Supply Store',
         'image': 'Farm_Supply_Store',
         'comment': 'Store for shelves, barrels, other containers, but not currently open for business',
#         'microphone': {True: 'friendly',
#                        False: 'friendly'},
         'NBCsensor': {True: False,
                       False: False},
        },
        ],
    [ # Level 4
	{'name': 'Antique Shop',
         'image': 'Furniture_Store',
         'comment': 'Store owner gossiping with delivery man',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'start': True,
        },
	{'name': 'Unrented Store',
         'image': 'Empty_Storage_Room',
         'comment': 'Small shop space, currently without a tenant',
        },
	{'name': 'Central Mosque',
         'image': 'Blue_Mosque',
         'comment': 'Filled with people doing their daily prayers',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },                           
	{'name': 'Sympathizer\'s House',
         'image': 'Poster-Room',
         'comment': 'Meeting attendees have recently fled, leaving only an empty room',
         'symbol': 'Sympathizer',
        },
        {'name': 'High School',
         'image': 'Wall-Table-Room',
         'comment': 'Empty rooms, classes have ended for the day',
        },
	{'name': 'Hardware Store',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Surprised armed insurgents, who were holding the hostage',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Local Newspaper',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Run by insurgent sympathizers, including two armed gunmen',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
	{'name': 'Contractor\'s Office',
         'image': 'Farm_Supply_Store',
         'comment': 'Small meeting space, containing nothing dangerous',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: False,
                       False: False},
         'symbol': 'ContractorsOffice',
        },
	{'name': 'Synagogue',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Armed gunman broke in through back door',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Middle School',
         'image': 'Cracked-Wall-Room',
         'comment': 'No threats in any of the rooms or hallways',
        },
	{'name': 'Construction Site',
         'image': 'Farm_Supply_Store_danger',
         'comment': 'Radioative materials being stored in temporary office',
         'NBC': True,
         'NBCsensor': {True: True,
                       False: True},
        },
	{'name': 'Fortune Teller\'s Rooms',
         'image': 'Chat-Room',
         'comment': 'Nervous customers waiting their turn',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'FortuneTellersRooms',
        },
	{'name': 'Lawyer\'s Office',
         'image': 'Carpet-Room',
         'comment': 'No people present, nor any dangerous chemicals',
         'symbol': 'LawyersOffice',
        },
	{'name': 'Council Chambers',
         'image': 'Suspected_Safe_House',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'After-hours civic planning session of council committee',
        },
	{'name': 'Informant\'s House',
         'image': 'Informant\'s_House',
         'comment': 'Male civilian in need of medical attention',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'InformantsHouse',
        },
        ],
    [ # Level 5
	{'name': 'Grand Mosque',
         'comment': 'Currently empty of civilians. Nothing of interest',
         'image': 'Yellow_Mosque',
         'start': True,
        },
	{'name': 'International Hotel',
         'image': 'Doctor\'s_Office',
         'comment': 'Other than registration clerks, nothing to note in lobby',
        },
	{'name': 'Slum Building',
         'image': 'Cracked-Wall-Room',
         'comment': 'Crumbling walls, with no tenants or threats',
        },
	{'name': 'Bicycle Store',
         'image': 'Empty_Storage_Room',
         'comment': 'Closed-down bicycle shop with nothing to sell',
        },
	{'name': 'Shrine of Ali',
         'image': 'Blue_Mosque',
         'comment': 'Murmuring prayers of peaceful worshippers',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Masonry Store',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Seized by armed insurgents, who used it to hide the hostage',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Hospital',
         'image': 'Informant\'s_House',
         'comment': 'Distressed women demanding medical attention for man waiting in ER',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Mayor\'s Balcony',
         'image': 'Potential_Sniper_Spot',
         'comment': 'Unoccupied rooftop deck with nothing of interest',
         'symbol': 'MayorsBalcony',
        },
	{'name': 'Indian Restaurant',
         'image': 'Auto_Parts_Store',
         'comment': 'Owner and workers finishing construction of interior',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Real Estate Office',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Front for insurgency headquarters',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
	{'name': 'Grocery Store',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Attacked by armed insurgent, who just broke in through employee entrance',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Movie Theater',
         'image': 'Gas_Room',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'Janitorial supplies for use by the ushers between showings',
        },
	{'name': 'Night Club',
         'image': 'Cafe_danger',
         'comment': 'IED lab in back room, unbeknownst to legitimate patrons in front',
         'NBC': True,
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: True,
                       False: True},
        },
	{'name': 'Clothing Boutique',
         'image': 'Black_Market',
         'comment': 'Multiple stalls, selling imported clothing at high prices',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Potential Sniper Spot',
         'image': 'Potential_Sniper_Spot_hostage',
         'comment': 'On rooftop deck, hostage being guarded by man who surrendered immediately',
         'hostage': True,
         'symbol': 'SniperSpot',
        },
        ],
    [ # Level 6
	{'name': 'Plumber\'s Office',
         'image': 'Farm_Supply_Store_danger',
         'comment': 'Chemical/biological agents being stored for use by insurgency',
         'NBC': True,
         'NBCsensor': {True: True,
                       False: True},
         'symbol': 'PlumbersOffice',
         'start': True,
        },
	{'name': 'Music Store',
         'image': 'Gas_Room',
         'comment': 'Cluttered rooms, but nothing out of the ordinary',
        },
	{'name': 'Judge\'s House',
         'image': 'Suspected_Safe_House',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'Interrupted civic leaders enjoying their time off together',
         'symbol': 'JudgesHouse',
        },
	{'name': 'Oil Company Office',
         'image': 'Farm_Supply_Store',
         'comment': 'Currently unoccupied; no threats identified',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: False,
                       False: False},
        },
	{'name': 'Convenience Store',
         'image': 'Black_Market',
         'comment': 'Man selling small items of clothing and luggage, of questionable legality',
        },
	{'name': 'Green Mosque',
         'image': 'Blue_Mosque',
         'comment': 'Not as many worshippers as usual, but nothing suspicious',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },                           
	{'name': 'Library',
         'image': 'City_Office',
         'comment': 'Crowded checkout lines, but nobody of interest',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Youth Center',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Assaulted by armed insurgents, who were hiding the hostage in one of the rooms',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Hookah Lounge',
         'image': 'Cafe',
         'comment': 'Men upset at having their relaxation interrupted',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Courthouse Lobby',
         'image': 'Doctor\'s_Office',
         'comment': 'Empty waiting area within city courthouse',
        },
	{'name': 'Temp Agency',
         'image': 'Chat-Room',
         'comment': 'Workers awaiting job assignments',
        },
	{'name': 'Shopping Center',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Armed insurgent hiding in janitor\'s closet',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Bank',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Two armed robbers laying in wait in lobby',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
	{'name': 'Scenice Overlook',
         'image': 'Potential_Sniper_Spot',
         'comment': 'Unobstructed views over the market, but nothing suspicious observed',
        },
	{'name': 'Imam\'s House',
         'image': 'Informant\'s_House',
         'comment': 'Female civilians outraged at the intrusion',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'ImamsHouse',
        },
        ],
    [ # Level 7
        {'name': 'Evidence Locker',
         'image': 'Black_Market',
         'comment': 'Holdings of goods confiscated from various raids on insurgents',
        },
        {'name': 'Gentleman\'s Club',
         'image': 'Cafe',
         'comment': 'Civilians drinking and smoking, but no one dangerous',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'MensClub',
        },
	{'name': 'Pediatrician\'s Office',
         'image': 'Chat-Room',
         'comment': 'Nervous parents awaiting their child\'s return',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'PediatriciansOffice',
        },
	{'name': 'Foreman\'s Office',
         'image': 'Empty_Storage_Room',
         'comment': 'Empty storage that serves as office of foreman of construction team.',
         'symbol': 'ForemansOffice',
        },
        {'name': 'Police Classroom',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Attacked by armed insurgents as well as sympathizers',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Room For Rent',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Armed insurgent hiding in unoccupied room put up for rent by homeowner',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Travel Agency',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Fired upon by two insurgents, who were ransacking the office',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
        {'name': 'Planning Office',
         'image': 'Wall-Table-Room',
         'comment': 'City planners have already left for the day.',
        },
	{'name': 'Consulate',
         'image': 'City_Office',
         'comment': 'Impatient would-be travelers, waiting to apply for a visa',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Victim\'s House',
         'image': 'Informant\'s_House',
         'comment': 'Female civilians outraged at innocent civilian inadvertently wounded by coalition forces',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'symbol': 'VictimsHouse',
        },
        {'name': 'Army Recruiting Center',
         'image': 'Poster-Room',
         'comment': 'Empty office with motivational poster to recruit local soldiers',
        }, 
        {'name': 'Drug Lab',
         'image': 'Cafe_danger',
         'comment': 'Small-scale drug operation, with many toxic IED chemicals',
         'NBC': True,
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'NBCsensor': {True: True,
                       False: True},
        },
	{'name': 'Restaurant',
         'image': 'Suspected_Safe_House',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'Civilians having dinner in private room',
        },
	{'name': 'Art Studio',
         'image': 'Furniture_Store',
         'comment': 'Proprietors preparing for a small exhibit',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Tannery',
         'image': 'Gas_Room',
         'comment': 'Industrial spill, but not of any dangerous chemical',
        },
        ],
    [ # Level 8
        {'name': 'Rooftop Deck',
         'image': 'Potential_Sniper_Spot',
         'comment': 'Unoccupied rooftop deck with nothing of interest',
        },
        {'name': 'Department Store',
         'image': 'City_Office',
         'comment': 'Angry shoppers waiting in the returns line',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
	{'name': 'Quran Study Group',
         'image': 'Suspected_Safe_House',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
         'comment': 'A reading group having a religious argument.',
        },
        {'name': 'Power Plant',
         'image': 'Farm_Supply_Store_danger',
         'comment': 'Improperly sealed drums of industrial wasted have led to an unsafe environment',
         'NBC': True,
         'NBCsensor': {True: True,
                       False: True},
         'symbol': 'FarmSupply',
        },
	{'name': 'Community Center',
         'image': 'Wall-Table-Room',
         'comment': 'Notes from disccusions by local activists',
        },
	{'name': 'Islamic School',
         'image': 'Poster-Room',
         'comment': 'Empty classrooms, with miscellaneous fundamentalist messages',
        },
	{'name': 'Transportation Control Room',
         'image': 'Auto_Parts_Store_danger',
         'comment': 'Shot at by security forces, hired by organized crime to protect their black market interests',
         'hostage': True,
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
        },
	{'name': 'Police Station',
         'image': 'Gas_Room',
         'comment': 'The safest building in the city, so far',
        },
        {'name': 'Charity Dropoff',
         'image': 'Black_Market',
         'comment': 'NGO worker collecting donations of clothing, foods, etc.',
        },
        {'name': 'Photography Studio',
         'image': 'Furniture_Store',
         'comment': 'Customer discussion photography project with salesman.',
         'microphone': {True: 'friendly',
                        False: 'friendly'},
        },
        {'name': 'Bowling Alley',
         'image': 'Cracked-Wall-Room',
         'comment': 'Graffiti in private access way, but no sign of who was theere.',
        },
	{'name': 'Carpentry Firm',
         'image': 'Doctor\'s_Office_danger',
         'comment': 'Two men immediately rose and strated firing at me as I entered.',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera':{True: True,
                   False: False},
        },
        {'name': 'Hostel',
         'image': 'Empty_Storage_Room_danger',
         'comment': 'Stumbled upon armed insurgent, holed up in small room',
         'armed': True,
         'microphone': {True: 'suspicious',
                        False: 'suspicious'},
         'camera': {True: True,
                    False: False},
         },
        {'name': 'Daycare Center',
         'image': 'Carpet-Room',
         'comment': 'Unoccupied building, as all children have already been picked up',
        },
        {'name': 'Market City Mosque',
         'image': 'Yellow_Mosque',
         'comment': 'Empty mosque, between services',
        },
    ],
]

SAFE = [
    {'name': 'Auto Parts Store',
     'image': 'Auto_Parts_Store',
     'comment': 'Salesmen and customers in front room',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
    },
    {'name': 'Black Market',
     'image': 'Black_Market',
     'comment': 'Unarmed man illegally selling clothing in the back room',
    },
    {'name': 'Blue Mosque',
     'image': 'Blue_Mosque',
     'comment': 'Filled with people doing their daily prayers',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
    },                           
    {'name': 'Mosque',
     'image': 'Blue_Mosque_hostage',
     'comment': 'Peaceful female civilians praying in front, hostage found restrained in corner behind screen',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
     'hostage': True,
    },
    {'name': 'Opium Den',
     'image': 'Cafe',
     'comment': 'Hookah smoke and customers, but nothing dangerous',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
    },
    {'name': 'Cleric\'s House',
     'image': 'Carpet-Room',
     'comment': 'Unoccupied building, seemingly abandoned',
     'symbol': 'ClericsHouse',
    },
    {'name': 'Fortune Teller\'s Rooms',
     'image': 'Chat-Room',
     'comment': 'Nervous customers waiting their turn',
     'symbol': 'FortuneTellersRooms',
    },
    {'name': 'Unemployment Office',
     'image': 'City_Office',
     'comment': 'Angry civilians waiting in line, but not violent',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
    },
    {'name': 'Back Alley',
     'image': 'Cracked-Wall-Room',
     'comment': 'Unoccupied corridor between two buildings',
    },
    {'name': 'Courthouse Lobby',
     'image': 'Doctor\'s_Office',
     'comment': 'Empty waiting area within city courthouse',
    },
    {'name': 'Unrented Store',
     'image': 'Empty_Storage_Room',
     'comment': 'Small shop space, currently without a tenant',
    },
    {'name': 'Fuel Store',
     'image': 'Farm_Supply_Store',
     'comment': 'Safe other than some drums of fuel',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
     'NBCsensor': {True: False,
                   False: False},
    },
    {'name': 'Furniture Store',
     'image': 'Furniture_Store',
     'comment': 'Salesman and customer haggling in furniture showroom',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
    },
    {'name': 'General  Store',
     'image': 'Gas_Room',
     'comment': 'Oil spill in storage room of general store, but nothing dangerous',
    },
    {'name': 'Informant\'s House',
     'image': 'Informant\'s_House',
     'comment': 'Male civilian in need of medical attention',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
     'symbol': 'InformantsHouse',
    },
    {'name': 'Sympathizer\'s House',
     'image': 'Poster-Room',
     'comment': 'Meeting attendees have already fled, leaving only an empty room',
     'symbol': 'Sympathizer',
    },
    {'name': 'Potential Sniper Spot',
     'image': 'Potential_Sniper_Spot',
     'comment': 'Unoccupied rooftop deck with nothing of interest',
     'start': True,
     'symbol': 'SniperSpot',
    },
    
    {'name': 'Potential Sniper Spot',
     'image': 'Potential_Sniper_Spot_hostage',
     'comment': 'On rooftop deck, hostage being guarded by man who surrendered immediately',
     'hostage': True,
     'symbol': 'SniperSpot',
    },
    {'name': 'Suspected Safe House',
     'image': 'Suspected_Safe_House',
     'microphone': {True: 'friendly',
                    False: 'friendly'},
     'comment': 'Civilians having private dinner and a friendly argument',
     'symbol': 'SafeHouse',
    },
    {'name': 'Conference Center',
     'image': 'Wall-Table-Room',
     'comment': 'Traces of a previous meeting and presentation',
    },
    {'name': 'Yellow Mosque',
     'comment': 'Currently empty of civilians. Nothing of interest',
     'image': 'Yellow_Mosque',
    },
]

ARMED = [
    {'name': 'Animal Feed Store',
     'image': 'Auto_Parts_Store_danger',
     'comment': 'Taken over by armed insurgents who were hiding the hostage',
     'hostage': True,
     'armed': True,
     'microphone': {True: 'suspicious',
                    False: 'suspicious'},
     'camera': {True: True,
                False: False},
    },
    {'name': 'Doctor\'s Office',
     'image': 'Doctor\'s_Office_danger',
     'comment': 'Occupied by two armed insurgents',
     'armed': True,
     'microphone': {True: 'suspicious',
                    False: 'suspicious'},
     'camera':{True: True,
               False: False},
     'symbol': 'DoctorsOffice',
    },
    {'name': 'City Office',
     'image': 'Empty_Storage_Room_danger',
     'comment': 'Armed insurgent in back room of city office building',
     'armed': True,
     'microphone': {True: 'suspicious',
                    False: 'suspicious'},
     'camera': {True: True,
                False: False},
    },
]

NBC = [
    {'name': 'Hookah Cafe',
     'image': 'Cafe_danger',
     'comment': 'Hookah smoke being used to mask the smell of toxic chemicals',
     'NBC': True,
     'microphone': {True: 'friendly',
                    False: 'friendly'},
     'NBCsensor': {True: True,
                   False: True},
    },
    {'name': 'Farm Supply Store',
     'image': 'Farm_Supply_Store_danger',
     'comment': 'Toxic chemicals being stored in open drums',
     'NBC': True,
     'NBCsensor': {True: True,
                   False: True},
     'symbol': 'FarmSupply',
    },
]

OLDWAYPOINTS = [
    # Level 1
    [{'name': 'Yellow Mosque',
      'comment': 'Currently empty of civilians. Nothing of interest',
      'start': True,
  },
     {'name': 'Informant\'s House',
      'comment': 'Male civilian in need of medical attention',
      'symbol': 'InformantsHouse',
  },
     {'name': 'Auto Parts Store',
      'comment': 'Salesmen and customers in front room, black market clothing dealer in back',
  },
     {'name': 'Cafe',
      'comment': 'Hookah smoke and customers, but nothing dangerous',
  },
     {'name': 'Doctor\'s Office',
      'comment': 'Occupied by two armed insurgents',
      'armed': True,
      'observe':{True: 'armed',
                 False: 'none'},
      'symbol': 'DoctorsOffice',
  },
     {'name': 'City Office',
      'comment': 'Angry civilians waiting in line, but not violent',
  },
     {'name': 'Farm Supply Store',
      'comment': 'Toxic chemicals being stored in open drums',
      'NBC': True,
      'observe': {True: 'NBC',
                  False: 'NBC'},
      'symbol': 'FarmSupply',
  },
     {'name': 'Blue Mosque',
      'comment': 'Peaceful female civilians praying in front, hostage found restrained in corner behind screen',
      'hostage': True,
  },
 ],
    # Level 2
    [{'name': 'Yellow Mosque',
      'comment': 'Currently empty of civilians. Nothing of interest',
     },
     {'name': 'Auto Parts Store',
      'comment': 'Salesmen and customers in front room, black market clothing dealer in back',
     },
     {'name': 'Cafe',
      'comment': 'Hookah smoke being used to mask the smell of toxic chemicals',
      'NBC': True,
      'observe': {True: 'NBC',
                  False: 'NBC'},
     },
     {'name': 'Doctor\'s Office',
      'comment': 'Occupied by two armed insurgents',
      'armed': True,
      'observe': {True: 'armed',
                  False: 'none'},
      'symbol': 'DoctorsOffice',
     },
     {'name': 'Farm Supply Store',
      'comment': 'Safe other than some fertilizer and pesticides',
      'observe': {True: 'none',
                  False: 'none'},
      'symbol': 'FarmSupply',
     },
     {'name': 'Potential Sniper Spot',
      'comment': 'On rooftop deck, hostage being guarded by man who surrendered immediately',
      'hostage': True,
      'symbol': 'SniperSpot',
     },
     {'name': 'Suspected Safe House',
      'comment': 'Civilians having private dinner and a friendly argument',
      'symbol': 'SafeHouse',
     },
     {'name': 'Blue Mosque',
      'comment': 'Filled with people doing their daily prayers',
      'start': True,
     },                           
 ],
    # Level 3
    [{'name': 'Informant\'s House',
      'comment': 'Male civilian in need of medical attention',
      'symbol': 'InformantsHouse',
     },
     {'name': 'Auto Parts Store',
      'comment': 'Taken over by armed insurgents who were hiding the hostage',
      'hostage': True,
      'armed': True,
      'observe': {True: 'armed',
                  False: 'none'},
     },
     {'name': 'Doctor\'s Office',
      'comment': 'Empty office with no doctor or patients currently present',
      'symbol': 'DoctorsOffice',
     },
     {'name': 'City Office',
      'comment': 'Angry civilians protecting armed insurgent in back room',
      'armed': True,
      'observe': {True: 'armed',
                  False: 'none'},
     },
     {'name': 'Furniture Store',
      'comment': 'Salesman and customer haggling in furniture showroom',
     },
     {'name': 'Farm Supply Store',
      'comment': 'Toxic chemicals being stored in open drums',
      'NBC': True,
      'observe': {True: 'NBC',
                  False: 'NBC'},
      'symbol': 'FarmSupply',
     },
     {'name': 'Potential Sniper Spot',
      'comment': 'Unoccupied rooftop deck with nothing of interest',
      'start': True,
      'symbol': 'SniperSpot',
     },
     {'name': 'Suspected Safe House',
      'comment': 'Civilians having private dinner and a friendly argument',
      'symbol': 'SafeHouse',
  },
 ],
     ]

def dangerp(room,category=None):
    if category is None:
        return dangerp(room,'armed') or dangerp(room,'NBC')
    else:
        return room.has_key(category) and room[category] is True

def genLevel(freq):
    NUMBUILDINGS = 15
    import random

    while True:
        level = [None for i in range(NUMBUILDINGS)]
        # Insert all buildings with armed gunmen (i.e., robot errors)
        # Don't have robot errors for first 3 buildings
        positions = random.sample(range(3,NUMBUILDINGS),len(ARMED))
        for i in range(len(ARMED)):
            level[positions[i]] = ARMED[i]
            # Fill in the remaining buildings
        buildings = random.sample(SAFE+NBC,NUMBUILDINGS-len(ARMED))
        ok = False
        for i in range(NUMBUILDINGS):
            if level[i] is None:
                level[i] = buildings.pop()
                if dangerp(level[i],'NBC'):
                    # Make sure we have at least one NBC building
                    ok = True
        if ok:
            return level
    
def genLevels():
    levels = []
    # Let's keep track of how often we're using buildings
    counts = {}
    for building in SAFE+NBC+ARMED:
        counts[building['image']] = 0
    while len(levels) < 6:
        level = genLevel()
        levels.append(level)
        for building in level:
            counts[building['image']] += 1
    for i in range(len(levels)):
        level = levels[i]
        print 'Level %d' % (i+1)
        for building in level:
            print '\t%s: %s %s' % (building['name'],dangerp(building,'armed'),
                                      dangerp(building,'NBC'))
        
    for building in SAFE+NBC:
        print '%d %s' % (counts[building['image']],building['image'])
    return levels

def countBuildings():
    count = {}
    for level in range(len(WAYPOINTS)):
        print 'Level %d' % (level+1)
        for building in WAYPOINTS[level]:
            try:
                count[building['image']] += 1
            except KeyError:
                count[building['image']] = 1
    return count

if __name__ == '__main__':
    used = {}
    for level in range(len(WAYPOINTS)):
        print 'Level %d' % (level+1)
        for building in WAYPOINTS[level]:
            print '\t',building['name']
            assert not used.has_key(building['name']),'%s has already appeared' % (building['name'])
            used[building['name']] = True
    count = countBuildings()
    for key in sorted(count.keys()):
        print '\t',key,count[key]
#    WAYPOINTS.append(genLevel(count))
#    count = countBuildings()
#    WAYPOINTS.append(genLevel(count))
#    for level in range(len(WAYPOINTS)):
#        print 'Level %d' % (level+1)
#        for building in WAYPOINTS[level]:
#            print '\t',building['image']
#    count = countBuildings()
#    for key in sorted(count.keys()):
#        print '\t',key,count[key]
